### ISSUE TITLE
I met a new issues when I execute " mvn -DiskipTests " in  "C:\Users\P0079482.HHDOMAIN\odl-sparkbot\sparkbot" with the following image

### ISSUE THREAD

**Issue by weizhenzhao** [CiscoDevNet/awesome-ciscospark#24]
![sparkbot_mvn_install](https://user-images.githubusercontent.com/13706689/30055546-654e2756-9262-11e7-8ad1-39fc933267aa.PNG)

**Comment by dstaudt** [comment]
The project for developing the old-sparkbot code is here: https://github.com/CiscoDevNet/odl-sparkbot/issues.  Please open an issue with this 'upstream' project for troubleshooting.
