### ISSUE TITLE
Dissociate Chat/Messaging from Calls/Video examples

### ISSUE THREAD

**Issue by ObjectIsAdvantag** [CiscoDevNet/awesome-ciscospark#28]
Thinking the UX would be enhanced if the ChatBot / Video entries were dissociated

**Comment by olivierproffit** [comment]
agree. Or a tag or flag to specify which are providing messaging or calling or both.

**Comment by ObjectIsAdvantag** [comment]
Here is an attempt:
https://github.com/CiscoDevNet/awesome-ciscospark/tree/sdks

Happy to get your feedback @olivierproffit

**Comment by ObjectIsAdvantag** [comment]
Integrated in new TOC
=> closing
