### ISSUE TITLE
Can webex bot return some message when webhook not work or app server timeout?

### ISSUE THREAD

**Issue by SincerelyUnique** [CiscoDevNet/awesome-ciscospark#85]
I'd like to ask a simple question, can webex bot return some message for users when webhook not work or app server request timeout. I think it will be more friendly to users.
Just like return "Sorry, webhook not work currently, please try later!" or "The app server has some interal errors, please contact xxx for help!"

Thanks! :)

**Comment by ObjectIsAdvantag** [comment]
hi @SincerelyUnique, interesting, this behavior would need to be added on the webex cloud platform when processing webhooks. To send this feature request to the Webex API group, you can send an email to devsupport@webex.com. 

That being said, I agree there is a gap in the user experience when it comes to bots. I started a spec and experimenting with metadata for bots a few years ago, you may want to look at it: https://github.com/BotCommons/BotCommons-Specification
If you saw some similar initiative getting traction in the industry, please keep me posted!

**Comment by dstaudt** [comment]
The Webex Teams webhook system does track whether webhooks are being delivered successfully, and will mark a webhook with status = false if multiple deliveries fail.  If you bot has not received a webhook in some time, it could go ahead and perform a GET /webhooks to check whether its webhook status is still active.  If not, then inform a user, and/or try to delete/re-create the webhook...

**Comment by SincerelyUnique** [comment]
> The Webex Teams webhook system does track whether webhooks are being delivered successfully, and will mark a webhook with status = false if multiple deliveries fail. If you bot has not received a webhook in some time, it could go ahead and perform a GET /webhooks to check whether its webhook status is still active. If not, then inform a user, and/or try to delete/re-create the webhook...

Hi dstaudt, Sometimes the service on our production line will be stopped for some reason. At this time, when the user is using the bot, he will wait for a long time and receive no messages. We hope to be able to return some messages in this case to remind the user not to continue to wait. , Can we send a message to the user in this case. :)

**Comment by SincerelyUnique** [comment]
> hi @SincerelyUnique, interesting, this behavior would need to be added on the webex cloud plateform when processing webhooks. To send this feature request to the Webex APUI group, you can send an email to [devsupport@webex.com](mailto:devsupport@webex.com).
> 
> That being said, I agree there is a gap in the user experience when it comes to bots. I started a spec and experimenting with metadata for bots a few years ago, you may want to look at it: https://github.com/BotCommons/BotCommons-Specification
> If you saw some similar initiative getting traction in the industry, please keep me posted!

Thanks @ObjectIsAdvantag I will send an email to devsupport@webex.com.

**Comment by SincerelyUnique** [comment]
From Webex Developer Support(devsupport@webex.com) said, there is no way have the bot send some sort of default reply to a user if the webhook is disabled or the server hosting the bot code is down. This would require some custom logic on my side(but my server maybe down already), and suggest me set up a watcher code on our server like health check(if server is down, the code is also useless), So in this case, we have no solution (we cannot reminder user not  continue to wait when bot is down), sorry!
